import Container from "@mui/material/Container";
import Head from "next/head";
import FullData from "../components/FullData";
import QuickView from "../components/QuickView";
import Summary from "../components/Summary";
import SearchBar from "@/components/SearchBar";
export default function Home({
  SearchBar,
  selectedSummary,
  selectedQuickView,
  selectedFullData,
}) {
  return (
    <>
      <Head>
        <title>Player Profiles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Container
          maxWidth="lg"
          sx={{
            display: "flex",
            justifyContent: "center",
            marginTop: "2rem",
          }}
        >
          {selectedSummary && <Summary />}
          {selectedQuickView && <QuickView />}
          {selectedFullData && <FullData />}
        </Container>
      </main>
    </>
  );
}
