const FullDataTable = (currentPlayer, percentileScores, playerGrades) => {
  return [
    {
      title: "Opportunity & Usage",
      vsaverage: true,
      stats: [
        [
          1,
          "Minutes/Game",
          currentPlayer["Minutes/Game"],
          percentileScores["Minutes/Game"],
          playerGrades["Minutes/Game"],
        ],
        [
          2,
          "Percent of Games Started",
          currentPlayer["Games Started_pct"],
          percentileScores["Games Started_pct"],
          playerGrades["Games Started_pct"],
        ],
        [
          2,
          "Touches/Game",
          currentPlayer["Touches/Game"],
          percentileScores["Touches/Game"],
          playerGrades["Touches/Game"],
        ],
        [
          3,
          "Scoring Possessions / 75",
          currentPlayer["Scoring Possessions / 75"],
          percentileScores["Scoring Possessions / 75"],
          playerGrades["Scoring Possessions / 75"],
        ],
        [
          3,
          "Ball Dominance",
          currentPlayer["Ball Dominance_pct"],
          percentileScores["Ball Dominance_pct"],
          playerGrades["Ball Dominance_pct"],
        ],
        [
          3,
          "Usage Rate",
          currentPlayer["Usage Rate_pct"],
          percentileScores["Usage Rate_pct"],
          playerGrades["Usage Rate_pct"],
        ],
        [
          3,
          "True Usage",
          currentPlayer["True Usage_pct"],
          percentileScores["True Usage_pct"],
          playerGrades["True Usage_pct"],
        ],
        [
          3,
          "Total Offensive Load",
          currentPlayer["Total Offensive Load_pct"],
          percentileScores["Total Offensive Load_pct"],
          playerGrades["Total Offensive Load_pct"],
        ],
      ],
    },
    {
      title: "Contextual Data",
      vsaverage: false,
      stats: [
        [
          1,
          "Lineup Finishing",
          currentPlayer["Lineup Finishing_pct"],
          percentileScores["Lineup Finishing_pct"],
          playerGrades["Lineup Finishing_pct"],
        ],
        [
          2,
          "Lineup Playmaking",
          currentPlayer["Lineup Playmaking_pct"],
          percentileScores["Lineup Playmaking_pct"],
          playerGrades["Lineup Playmaking_pct"],
        ],
        [
          2,
          "Lineup Spacing",
          currentPlayer["Lineup Spacing_pct"],
          percentileScores["Lineup Spacing_pct"],
          playerGrades["Lineup Spacing_pct"],
        ],
        [
          3,
          "Matchup Difficulty",
          currentPlayer["Matchup Difficulty"],
          percentileScores["Matchup Difficulty"],
          playerGrades["Matchup Difficulty"],
        ],
        [
          3,
          "D Position Versatility",
          currentPlayer["Defensive Positional Versatility"],
          percentileScores["Defensive Positional Versatility"],
          playerGrades["Defensive Positional Versatility"],
        ],
        [
          3,
          "D Role Versatility",
          currentPlayer["Defensive Role Versatility"],
          percentileScores["Defensive Role Versatility"],
          playerGrades["Defensive Role Versatility"],
        ],
        [
          3,
          "Foul Trouble Percentage",
          currentPlayer["Foul Trouble_pct"],
          percentileScores["Foul Trouble_pct"],
          playerGrades["Foul Trouble_pct"],
        ],
      ],
    },
    {
      title: "Perimeter Shooting",
      vsaverage: false,
      stats: [
        [
          1,
          "3PT%",
          currentPlayer["3PT_pct"],
          percentileScores["3PT_pct"],
          playerGrades["3PT_pct"],
        ],
        [
          2,
          "Pull Up 3PT%",
          currentPlayer["Pull Up 3PT_pct"],
          percentileScores["Pull Up 3PT_pct"],
          playerGrades["Pull Up 3PT_pct"],
        ],
        [
          2,
          "C&S 3PT%",
          currentPlayer["C&S 3PT_pct"],
          percentileScores["C&S 3PT_pct"],
          playerGrades["C&S 3PT_pct"],
        ],
        [
          3,
          "ATB 3PT%",
          currentPlayer["ATB 3PT_pct"],
          percentileScores["ATB 3PT_pct"],
          playerGrades["ATB 3PT_pct"],
        ],
        [
          3,
          "Corner 3PT%",
          currentPlayer["Corner 3PT_pct"],
          percentileScores["Corner 3PT_pct"],
          playerGrades["Corner 3PT_pct"],
        ],
        [
          3,
          "Openness Rating",
          currentPlayer["3PT Openness Rating"],
          percentileScores["3PT Openness Rating"],
          playerGrades["3PT Openness Rating"],
        ],
        [
          3,
          "Percent of 3PTA Open",
          currentPlayer["3PTA Open_pct"],
          percentileScores["3PTA Open_pct"],
          playerGrades["3PTA Open_pct"],
        ],
        [
          3,
          "Avg. 3PT Shot Distance",
          currentPlayer["Avg. 3PT Shot Distance"],
          percentileScores["Avg. 3PT Shot Distance"],
          playerGrades["Avg. 3PT Shot Distance"],
        ],
        [
          3,
          "C&S : Pull Up Ratio",
          currentPlayer["C&S : Pull Up Ratio"],
          "",
          "",
        ],
        [
          3,
          "Corner 3: ATB Ratio",
          currentPlayer["Corner 3 : ATB Ratio"],
          "",
          "",
        ],
        [
          3,
          "3PT Shot Quality",
          currentPlayer["3PT Shot Quality"],
          percentileScores["3PT Shot Quality"],
          playerGrades["3PT Shot Quality"],
        ],
        [
          3,
          "3PT Foul Rate",
          currentPlayer["3PT Foul Rate_pct"],
          percentileScores["3PT Foul Rate_pct"],
          playerGrades["3PT Foul Rate_pct"],
        ],
        [
          3,
          "3PTA Rate",
          currentPlayer["3PTA Rate_pct"],
          percentileScores["3PTA Rate_pct"],
          playerGrades["3PTA Rate_pct"],
        ],
        [
          3,
          "3PT Shot Making",
          currentPlayer["3PT Shot Making"],
          percentileScores["3PT Shot Making"],
          playerGrades["3PT Shot Making"],
        ],
        [
          3,
          "3PT Shot Creation",
          currentPlayer["3PT Shot Creation"],
          percentileScores["3PT Shot Creation"],
          playerGrades["3PT Shot Creation"],
        ],
        [
          3,
          "Perimeter Shooting",
          currentPlayer["3PT Shooting Talent"],
          percentileScores["3PT Shooting Talent"],
          playerGrades["3PT Shooting Talent"],
        ],
      ],
    },
    {
      title: "One on One",
      vsaverage: false,
      stats: [
        [
          1,
          "Total Isolations / 75",
          currentPlayer["Total Isolations / 75"],
          percentileScores["Total Isolations / 75"],
          playerGrades["Total Isolations / 75"],
        ],
        [
          2,
          "Total Iso Impact / 75",
          currentPlayer["Total Iso Impact / 75"],
          percentileScores["Total Iso Impact / 75"],
          playerGrades["Total Iso Impact / 75"],
        ],
        [
          2,
          "Total Isolation eFG%",
          currentPlayer["Total Isolation eFG_pct"],
          percentileScores["Total Isolation eFG_pct"],
          playerGrades["Total Isolation eFG_pct"],
        ],
        [
          3,
          "Iso Foul Drawn Rate",
          currentPlayer["Iso Foul Drawn Rate_pct"],
          percentileScores["Iso Foul Drawn Rate_pct"],
          playerGrades["Iso Foul Drawn Rate_pct"],
        ],
        [
          3,
          "Isolation Turnover Rate",
          currentPlayer["Iso TO Rate_pct"],
          percentileScores["Iso TO Rate_pct"],
          playerGrades["Iso TO Rate_pct"],
        ],
        [3, "Perimeter Iso : Post Iso Ratio", "", "98% Outside", "2% Post"],
        [
          3,
          "Left Side : Right Side Isolation Ration",
          "",
          "41% Left",
          "59% Right",
        ],
      ],
    },
    {
      title: "Off Ball Movement",
      vsaverage: false,
      stats: [
        [
          1,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          2,
          "Movement Dist. Rating",
          currentPlayer["Movement Dist. Rating"],
          percentileScores["Movement Dist. Rating"],
          playerGrades["Movement Dist. Rating"],
        ],
        [
          2,
          "Movement Speed Rating",
          currentPlayer["Movement Speed Rating"],
          percentileScores["Movement Speed Rating"],
          playerGrades["Movement Speed Rating"],
        ],
        [
          3,
          "Movement Pts. / 75 Poss",
          currentPlayer["Movement Pts. / 75 Poss"],
          percentileScores["Movement Pts. / 75 Poss"],
          playerGrades["Movement Pts. / 75 Poss"],
        ],
        [
          3,
          "Movement Impact / 75",
          currentPlayer["Movement Impact / 75"],
          percentileScores["Movement Impact / 75"],
          playerGrades["Movement Impact / 75"],
        ],
        [
          3,
          "Off Screen Poss/ 75 Poss",
          currentPlayer["Off Screen Poss/ 75 Poss"],
          percentileScores["Off Screen Poss/ 75 Poss"],
          playerGrades["Off Screen Poss/ 75 Poss"],
        ],
        [
          3,
          "Off Screen Share_pct",
          currentPlayer["Off Screen Share_pct"],
          percentileScores["Off Screen Share_pct"],
          playerGrades["Off Screen Share_pct"],
        ],
        [
          3,
          "Off Screen eFG_pct",
          currentPlayer["Off Screen eFG_pct"],
          percentileScores["Off Screen eFG_pct"],
          playerGrades["Off Screen eFG_pct"],
        ],
        [
          3,
          "Straight : Fade : Flare : Curl Ratio",
          currentPlayer["Straight : Fade : Flare : Curl Ratio"],
          "",
          "",
        ],
        [
          3,
          "Cuts/75",
          currentPlayer["Cuts/75"],
          percentileScores["Cuts/75"],
          playerGrades["Cuts/75"],
        ],
        [
          3,
          "Cut Share_pct",
          currentPlayer["Cut Share_pct"],
          percentileScores["Cut Share_pct"],
          playerGrades["Cut Share_pct"],
        ],
        [
          3,
          "Cut FG_pct",
          currentPlayer["Cut FG_pct"],
          percentileScores["Cut FG_pct"],
          playerGrades["Cut FG_pct"],
        ],
        [
          3,
          "Flash : Screen Cut Ratio",
          currentPlayer["Flash : Screen Cut Ratio"],
          "",
          "",
        ],
      ],
    },
    {
      title: "Off Ball Movement",
      vsaverage: false,
      stats: [
        [
          1,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          2,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          2,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          3,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          3,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          3,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          3,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          3,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          3,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          3,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
        [
          3,
          "Movement Attack Rate_pct",
          currentPlayer["Movement Attack Rate_pct"],
          percentileScores["Movement Attack Rate_pct"],
          playerGrades["Movement Attack Rate_pct"],
        ],
      ],
    },
    {
      title: "Finishing",
      vsaverage: false,
      stats: [
        [
          1,
          "Drives / 75",
          currentPlayer["Drives / 75"],
          percentileScores["Drives / 75"],
          playerGrades["Drives / 75"],
        ],
        [
          2,
          "Total Shots at Rim / 75",
          currentPlayer["Total Shots at Rim / 75"],
          percentileScores["Total Shots at Rim / 75"],
          playerGrades["Total Shots at Rim / 75"],
        ],
        [
          2,
          "Unassisted Rim FGA / 75",
          currentPlayer["Unassisted Rim FGA / 75"],
          percentileScores["Unassisted Rim FGA / 75"],
          playerGrades["Unassisted Rim FGA / 75"],
        ],
        [
          3,
          "% of Rim Unassisted_pct",
          currentPlayer["% of Rim Unassisted_pct"],
          percentileScores["% of Rim Unassisted_pct"],
          playerGrades["% of Rim Unassisted_pct"],
        ],
        [
          3,
          "Rim Shot Creation",
          currentPlayer["Rim Shot Creation"],
          percentileScores["Rim Shot Creation"],
          playerGrades["Rim Shot Creation"],
        ],
        [
          3,
          "Drive Passout Rate_pct",
          currentPlayer["Drive Passout Rate_pct"],
          percentileScores["Drive Passout Rate_pct"],
          playerGrades["Drive Passout Rate_pct"],
        ],
        [
          3,
          "Drive Assist Rate_pct",
          currentPlayer["Drive Assist Rate_pct"],
          percentileScores["Drive Assist Rate_pct"],
          playerGrades["Drive Assist Rate_pct"],
        ],
        [
          3,
          "Drive Assist/Pass_pct",
          currentPlayer["Drive Assist/Pass_pct"],
          percentileScores["Drive Assist/Pass_pct"],
          playerGrades["Drive Assist/Pass_pct"],
        ],
        [
          3,
          "Drive Foul Drawn Rate_pct",
          currentPlayer["Drive Foul Drawn Rate_pct"],
          percentileScores["Drive Foul Drawn Rate_pct"],
          playerGrades["Drive Foul Drawn Rate_pct"],
        ],
        [
          3,
          "Contact Finish Rate_pct",
          currentPlayer["Contact Finish Rate_pct"],
          percentileScores["Contact Finish Rate_pct"],
          playerGrades["Contact Finish Rate_pct"],
        ],
        [
          3,
          "Rim FG_pct",
          currentPlayer["Rim FG_pct"],
          percentileScores["Rim FG_pct"],
          playerGrades["Rim FG_pct"],
        ],
        [
          3,
          "Rim Shot Quality",
          currentPlayer["Rim Shot Quality"],
          percentileScores["Rim Shot Quality"],
          playerGrades["Rim Shot Quality"],
        ],
        [
          3,
          "Rim Shot Making",
          currentPlayer["Rim Shot Making"],
          percentileScores["Rim Shot Making"],
          playerGrades["Rim Shot Making"],
        ],
        [
          3,
          "Finishing Talent",
          currentPlayer["Finishing Talent"],
          percentileScores["Finishing Talent"],
          playerGrades["Finishing Talent"],
        ],
      ],
    },
    {
      title: "Roll Gravity",
      vsaverage: false,
      stats: [
        [
          1,
          "Roll Man Poss / 75 Poss",
          currentPlayer["Roll Man Poss / 75 Poss"],
          percentileScores["Roll Man Poss / 75 Poss"],
          playerGrades["Roll Man Poss / 75 Poss"],
        ],
        [
          2,
          "Team Roll Man Share_pct",
          currentPlayer["Team Roll Man Share_pct"],
          percentileScores["Team Roll Man Share_pct"],
          playerGrades["Team Roll Man Share_pct"],
        ],
        [
          2,
          "Total Roll Man Impact / 75 Poss",
          currentPlayer["Total Roll Man Impact / 75 Poss"],
          percentileScores["Total Roll Man Impact / 75 Poss"],
          playerGrades["Total Roll Man Impact / 75 Poss"],
        ],
        [
          3,
          "Roll Impact / 75 Poss",
          currentPlayer["Roll Impact / 75 Poss"],
          percentileScores["Roll Impact / 75 Poss"],
          playerGrades["Roll Impact / 75 Poss"],
        ],
        [
          3,
          "Pop Impact / 75 Poss",
          currentPlayer["Pop Impact / 75 Poss"],
          percentileScores["Pop Impact / 75 Poss"],
          playerGrades["Pop Impact / 75 Poss"],
        ],
        [
          3,
          "Slip Impact / 75 Poss",
          currentPlayer["Slip Impact / 75 Poss"],
          percentileScores["Slip Impact / 75 Poss"],
          playerGrades["Slip Impact / 75 Poss"],
        ],
        [
          3,
          "Roll : Pop : Slip Ratio",
          currentPlayer["Roll : Pop : Slip Ratio"],
          percentileScores["Roll : Pop : Slip Ratio"],
          playerGrades["Roll : Pop : Slip Ratio"],
        ],
        [
          3,
          "Screen Assists / 75 Poss",
          currentPlayer["Screen Assists / 75 Poss"],
          percentileScores["Screen Assists / 75 Poss"],
          playerGrades["Screen Assists / 75 Poss"],
        ],
        [
          3,
          "Screening Talent",
          currentPlayer["Screening Talent"],
          percentileScores["Screening Talent"],
          playerGrades["Screening Talent"],
        ],
      ],
    },
    {
      title: "Playmaking",
      vsaverage: false,
      stats: [
        [
          1,
          "Assist Pts / 75 Poss",
          currentPlayer["Assist Pts / 75 Poss"],
          percentileScores["Assist Pts / 75 Poss"],
          playerGrades["Assist Pts / 75 Poss"],
        ],
        [
          2,
          "RA Pot Ast / 100",
          currentPlayer["RA Pot Ast / 100"],
          percentileScores["RA Pot Ast / 100"],
          playerGrades["RA Pot Ast / 100"],
        ],
        [
          2,
          "Pot. Ast. / 100 Passes",
          currentPlayer["Pot. Ast. / 100 Passes"],
          percentileScores["Pot. Ast. / 100 Passes"],
          playerGrades["Pot. Ast. / 100 Passes"],
        ],
        [
          3,
          "Passing Creation Volume",
          currentPlayer["Passing Creation Volume"],
          percentileScores["Passing Creation Volume"],
          playerGrades["Passing Creation Volume"],
        ],
        [
          3,
          "Passing Efficiency",
          currentPlayer["Passing Efficiency"],
          percentileScores["Passing Efficiency"],
          playerGrades["Passing Efficiency"],
        ],
        [
          3,
          "Passing Versatility",
          currentPlayer["Passing Versatility"],
          percentileScores["Passing Versatility"],
          playerGrades["Passing Versatility"],
        ],
        [
          3,
          "HV Assists / 75 Poss",
          currentPlayer["HV Assists / 75 Poss"],
          percentileScores["HV Assists / 75 Poss"],
          playerGrades["HV Assists / 75 Poss"],
        ],
        [
          3,
          "Passing Creation Quality",
          currentPlayer["Passing Creation Quality"],
          percentileScores["Passing Creation Quality"],
          playerGrades["Passing Creation Quality"],
        ],
        [
          3,
          "Box Creation",
          currentPlayer["Box Creation"],
          percentileScores["Box Creation"],
          playerGrades["Box Creation"],
        ],
        [
          3,
          "Scoring Gravity",
          currentPlayer["Scoring Gravity"],
          percentileScores["Scoring Gravity"],
          playerGrades["Scoring Gravity"],
        ],
        [
          3,
          "Playmaking Talent",
          currentPlayer["Playmaking Talent"],
          percentileScores["Playmaking Talent"],
          playerGrades["Playmaking Talent"],
        ],
      ],
    },
    {
      title: "Post Play",
      vsaverage: false,
      stats: [
        [
          1,
          "Total Post frequency_pct",
          currentPlayer["Total Post frequency_pct"],
          percentileScores["Total Post frequency_pct"],
          playerGrades["Total Post frequency_pct"],
        ],
        [
          2,
          "Paint Touches / 75",
          currentPlayer["Paint Touches / 75"],
          percentileScores["Paint Touches / 75"],
          playerGrades["Paint Touches / 75"],
        ],
        [
          2,
          "Jumper : To Rim : Hook : Up & Under",
          currentPlayer["Jumper : To Rim : Hook : Up & Under"],
          percentileScores["Jumper : To Rim : Hook : Up & Under"],
          playerGrades["Jumper : To Rim : Hook : Up & Under"],
        ],
        [
          3,
          "Baseline : Face Up : Middle Ratio",
          currentPlayer["Baseline : Face Up : Middle Ratio"],
          percentileScores["Baseline : Face Up : Middle Ratio"],
          playerGrades["Baseline : Face Up : Middle Ratio"],
        ],
        [
          3,
          "Left : Middle : Right Block Ratio",
          currentPlayer["Left : Middle : Right Block Ratio"],
          percentileScores["Left : Middle : Right Block Ratio"],
          playerGrades["Left : Middle : Right Block Ratio"],
        ],
        [
          3,
          "Post Pin Frequency",
          currentPlayer["Post Pin Frequency"],
          percentileScores["Post Pin Frequency"],
          playerGrades["Post Pin Frequency"],
        ],
        [
          3,
          "Post Style Rating",
          currentPlayer["Post Style Rating"],
          percentileScores["Post Style Rating"],
          playerGrades["Post Style Rating"],
        ],
        [
          3,
          "Post Up Draw Foul Rate_pct",
          currentPlayer["Post Up Draw Foul Rate_pct"],
          percentileScores["Post Up Draw Foul Rate_pct"],
          playerGrades["Post Up Draw Foul Rate_pct"],
        ],
        [
          3,
          "Post Up Impact / 75 Poss",
          currentPlayer["Post Up Impact / 75 Poss"],
          percentileScores["Post Up Impact / 75 Poss"],
          playerGrades["Post Up Impact / 75 Poss"],
        ],
        [
          3,
          "Pot. Assist / Post Poss_pct",
          currentPlayer["Pot. Assist / Post Poss_pct"],
          percentileScores["Pot. Assist / Post Poss_pct"],
          playerGrades["Pot. Assist / Post Poss_pct"],
        ],
      ],
    },
    {
      title: "Defensive Rebounding",
      vsaverage: false,
      stats: [
        [
          1,
          "Defensive Reb / 75 Poss",
          currentPlayer["Defensive Reb / 75 Poss"],
          percentileScores["Defensive Reb / 75 Poss"],
          playerGrades["Defensive Reb / 75 Poss"],
        ],
        [
          2,
          "DReb Per Game",
          currentPlayer["DReb Per Game"],
          percentileScores["DReb Per Game"],
          playerGrades["DReb Per Game"],
        ],
        [
          2,
          "DReb Chance / 75 Poss",
          currentPlayer["DReb Chance / 75 Poss"],
          percentileScores["DReb Chance / 75 Poss"],
          playerGrades["DReb Chance / 75 Poss"],
        ],
        [
          3,
          "Contested DReb_pct",
          currentPlayer["Contested DReb_pct"],
          percentileScores["Contested DReb_pct"],
          playerGrades["Contested DReb_pct"],
        ],
        [
          3,
          "DReb Positioning",
          currentPlayer["DReb Positioning"],
          percentileScores["DReb Positioning"],
          playerGrades["DReb Positioning"],
        ],
        [
          3,
          "Adj. Box Out Rate_pct",
          currentPlayer["Adj. Box Out Rate_pct"],
          percentileScores["Adj. Box Out Rate_pct"],
          playerGrades["Adj. Box Out Rate_pct"],
        ],
        [
          3,
          "Adj. DReb Success Rate_pct",
          currentPlayer["Adj. DReb Success Rate_pct"],
          percentileScores["Adj. DReb Success Rate_pct"],
          playerGrades["Adj. DReb Success Rate_pct"],
        ],
        [
          3,
          "Defensive Rebounding Conversion Skill",
          currentPlayer["Defensive Rebounding Conversion Skill"],
          percentileScores["Defensive Rebounding Conversion Skill"],
          playerGrades["Defensive Rebounding Conversion Skill"],
        ],
        [
          3,
          "Real Adjusted DReb Rate",
          currentPlayer["Real Adjusted DReb Rate"],
          percentileScores["Real Adjusted DReb Rate"],
          playerGrades["Real Adjusted DReb Rate"],
        ],
        [
          3,
          "Defensive Rebounding Talent",
          currentPlayer["Defensive Rebounding Talent"],
          percentileScores["Defensive Rebounding Talent"],
          playerGrades["Defensive Rebounding Talent"],
        ],
      ],
    },
    {
      title: "Offensive Rebounding",
      vsaverage: false,
      stats: [
        [
          1,
          "Offensive Reb / 75 Poss",
          currentPlayer["Offensive Reb / 75 Poss"],
          percentileScores["Offensive Reb / 75 Poss"],
          playerGrades["Offensive Reb / 75 Poss"],
        ],
        [
          2,
          "OReb Per Game",
          currentPlayer["OReb Per Game"],
          percentileScores["OReb Per Game"],
          playerGrades["OReb Per Game"],
        ],
        [
          2,
          "OReb Chance / 75 Poss",
          currentPlayer["OReb Chance / 75 Poss"],
          percentileScores["OReb Chance / 75 Poss"],
          playerGrades["OReb Chance / 75 Poss"],
        ],
        [
          3,
          "Contested OReb_pct",
          currentPlayer["Contested OReb_pct"],
          percentileScores["Contested OReb_pct"],
          playerGrades["Contested OReb_pct"],
        ],
        [
          3,
          "OReb Positioning",
          currentPlayer["OReb Positioning"],
          percentileScores["OReb Positioning"],
          playerGrades["OReb Positioning"],
        ],
        [
          3,
          "Putbacks / 75 Poss",
          currentPlayer["Putbacks / 75 Poss"],
          percentileScores["Putbacks / 75 Poss"],
          playerGrades["Putbacks / 75 Poss"],
        ],
        [
          3,
          "Putback per OReb_pct",
          currentPlayer["Putback per OReb_pct"],
          percentileScores["Putback per OReb_pct"],
          playerGrades["Putback per OReb_pct"],
        ],
        [
          3,
          "Putback Impact / 75",
          currentPlayer["Putback Impact / 75"],
          percentileScores["Putback Impact / 75"],
          playerGrades["Putback Impact / 75"],
        ],
        [
          3,
          "Adj. OReb Success Rate_pct",
          currentPlayer["Adj. OReb Success Rate_pct"],
          percentileScores["Adj. OReb Success Rate_pct"],
          playerGrades["Adj. OReb Success Rate_pct"],
        ],
        [
          3,
          "Offensive Rebounding Conversion Skill",
          currentPlayer["Offensive Rebounding Conversion Skill"],
          percentileScores["Offensive Rebounding Conversion Skill"],
          playerGrades["Offensive Rebounding Conversion Skill"],
        ],
        [
          3,
          "Real Adjusted OReb Rate",
          currentPlayer["Real Adjusted OReb Rate"],
          percentileScores["Real Adjusted OReb Rate"],
          playerGrades["Real Adjusted OReb Rate"],
        ],
        [
          3,
          "Offensive Rebounding Talent",
          currentPlayer["Offensive Rebounding Talent"],
          percentileScores["Offensive Rebounding Talent"],
          playerGrades["Offensive Rebounding Talent"],
        ],
      ],
    },
    {
      title: "On-Ball Defense",
      vsaverage: false,
      stats: [
        [
          1,
          "On-Ball Defense",
          currentPlayer["On-Ball Defense"],
          percentileScores["On-Ball Defense"],
          playerGrades["On-Ball Defense"],
        ],
        [
          2,
          "Ball Screen Navigation",
          currentPlayer["Ball Screen Navigation"],
          percentileScores["Ball Screen Navigation"],
          playerGrades["Ball Screen Navigation"],
        ],
        [
          2,
          "Screener Mobile Defense",
          currentPlayer["Screener Mobile Defense"],
          percentileScores["Screener Mobile Defense"],
          playerGrades["Screener Mobile Defense"],
        ],
        [
          3,
          "Off-Ball Chaser Defense",
          currentPlayer["Off-Ball Chaser Defense"],
          percentileScores["Off-Ball Chaser Defense"],
          playerGrades["Off-Ball Chaser Defense"],
        ],
        [
          3,
          "Real Adjusted TOV Rate",
          currentPlayer["Real Adjusted TOV Rate"],
          percentileScores["Real Adjusted TOV Rate"],
          playerGrades["Real Adjusted TOV Rate"],
        ],
        [
          3,
          "Loose Ball Rec Rate",
          currentPlayer["Loose Ball Rec Rate"],
          percentileScores["Loose Ball Rec Rate"],
          playerGrades["Loose Ball Rec Rate"],
        ],
        [
          3,
          "Pickpocket Rating",
          currentPlayer["Pickpocket Rating"],
          percentileScores["Pickpocket Rating"],
          playerGrades["Pickpocket Rating"],
        ],
        [
          3,
          "Passing Lane Defense",
          currentPlayer["Passing Lane Defense"],
          percentileScores["Passing Lane Defense"],
          playerGrades["Passing Lane Defense"],
        ],
        [
          3,
          "3PT Contests / 75 Poss",
          currentPlayer["3PT Contests / 75 Poss"],
          percentileScores["3PT Contests / 75 Poss"],
          playerGrades["3PT Contests / 75 Poss"],
        ],
        [
          3,
          "Steals / 75 Poss",
          currentPlayer["Steals / 75 Poss"],
          percentileScores["Steals / 75 Poss"],
          playerGrades["Steals / 75 Poss"],
        ],
        [
          3,
          "Deflections / 75 Poss",
          currentPlayer["Deflections / 75 Poss"],
          percentileScores["Deflections / 75 Poss"],
          playerGrades["Deflections / 75 Poss"],
        ],
        [
          3,
          "Defensive Miles / 75",
          currentPlayer["Defensive Miles / 75"],
          percentileScores["Defensive Miles / 75"],
          playerGrades["Defensive Miles / 75"],
        ],
        [
          3,
          "Matchup Adj. D Feet/MP",
          currentPlayer["Matchup Adj. D Feet/MP"],
          percentileScores["Matchup Adj. D Feet/MP"],
          playerGrades["Matchup Adj. D Feet/MP"],
        ],
      ],
    },
    {
      title: "Playing Style",
      vsaverage: false,
      stats: [
        [
          1,
          "Primary Ball Handler_pct",
          currentPlayer["Primary Ball Handler_pct"],
          percentileScores["Primary Ball Handler_pct"],
          playerGrades["Primary Ball Handler_pct"],
        ],
        [
          2,
          "Secondary Ball Handlers_pct",
          currentPlayer["Secondary Ball Handlers_pct"],
          percentileScores["Secondary Ball Handlers_pct"],
          playerGrades["Secondary Ball Handlers_pct"],
        ],
        [
          2,
          "Shot Creators_pct",
          currentPlayer["Shot Creators_pct"],
          percentileScores["Shot Creators_pct"],
          playerGrades["Shot Creators_pct"],
        ],
        [
          3,
          "Slashers_pct",
          currentPlayer["Slashers_pct"],
          percentileScores["Slashers_pct"],
          playerGrades["Slashers_pct"],
        ],
        [
          3,
          "Athletic Finisher_pct",
          currentPlayer["Athletic Finisher_pct"],
          percentileScores["Athletic Finisher_pct"],
          playerGrades["Athletic Finisher_pct"],
        ],
        [
          3,
          "Off Screen Shooter_pct",
          currentPlayer["Off Screen Shooter_pct"],
          percentileScores["Off Screen Shooter_pct"],
          playerGrades["Off Screen Shooter_pct"],
        ],
        [
          3,
          "Movement Shooter_pct",
          currentPlayer["Movement Shooter_pct"],
          percentileScores["Movement Shooter_pct"],
          playerGrades["Movement Shooter_pct"],
        ],
        [
          3,
          "Stationary Shooters_pct",
          currentPlayer["Stationary Shooters_pct"],
          percentileScores["Stationary Shooters_pct"],
          playerGrades["Stationary Shooters_pct"],
        ],
        [
          3,
          "Versatile Bigs_pct",
          currentPlayer["Versatile Bigs_pct"],
          percentileScores["Versatile Bigs_pct"],
          playerGrades["Versatile Bigs_pct"],
        ],
        [
          3,
          "Post Scorer_pct",
          currentPlayer["Post Scorer_pct"],
          percentileScores["Post Scorer_pct"],
          playerGrades["Post Scorer_pct"],
        ],
        [
          3,
          "Stretch Bigs_pct",
          currentPlayer["Stretch Bigs_pct"],
          percentileScores["Stretch Bigs_pct"],
          playerGrades["Stretch Bigs_pct"],
        ],
        [
          3,
          "Roll & Cut Bigs_pct",
          currentPlayer["Roll & Cut Bigs_pct"],
          percentileScores["Roll & Cut Bigs_pct"],
          playerGrades["Roll & Cut Bigs_pct"],
        ],
        [
          3,
          "Low Minute_pct",
          currentPlayer["Low Minute_pct"],
          percentileScores["Low Minute_pct"],
          playerGrades["Low Minute_pct"],
        ],
      ],
    },
    {
      title: "Rim Protection",
      vsaverage: false,
      stats: [
        [
          1,
          "Rim Deterrence_pct",
          currentPlayer["Rim Deterrence_pct"],
          percentileScores["Rim Deterrence_pct"],
          playerGrades["Rim Deterrence_pct"],
        ],
        [
          2,
          "% Rim Shots Contested_pct",
          currentPlayer["% Rim Shots Contested_pct"],
          percentileScores["% Rim Shots Contested_pct"],
          playerGrades["% Rim Shots Contested_pct"],
        ],
        [
          2,
          "Rim Contests / 75 Poss",
          currentPlayer["Rim Contests / 75 Poss"],
          percentileScores["Rim Contests / 75 Poss"],
          playerGrades["Rim Contests / 75 Poss"],
        ],
        [
          3,
          "Blocks / 75 Poss",
          currentPlayer["Blocks / 75 Poss"],
          percentileScores["Blocks / 75 Poss"],
          playerGrades["Blocks / 75 Poss"],
        ],
        [
          3,
          "Block Rate on Contests_pct",
          currentPlayer["Block Rate on Contests_pct"],
          percentileScores["Block Rate on Contests_pct"],
          playerGrades["Block Rate on Contests_pct"],
        ],
        [
          3,
          "Rim dFG% vs Expected_pct",
          currentPlayer["Rim dFG% vs Expected_pct"],
          percentileScores["Rim dFG% vs Expected_pct"],
          playerGrades["Rim dFG% vs Expected_pct"],
        ],
        [
          3,
          "Rim Points Saved / 75 Post Defense",
          currentPlayer["Rim Points Saved / 75 Post Defense"],
          percentileScores["Rim Points Saved / 75 Post Defense"],
          playerGrades["Rim Points Saved / 75 Post Defense"],
        ],
        [
          3,
          "Screener Rim Defense",
          currentPlayer["Screener Rim Defense"],
          percentileScores["Screener Rim Defense"],
          playerGrades["Screener Rim Defense"],
        ],
        [
          3,
          "Rim Protection",
          currentPlayer["Rim Protection"],
          percentileScores["Rim Protection"],
          playerGrades["Rim Protection"],
        ],
      ],
    },
    {
      title: "Time on Defense by Position",
      vsaverage: false,
      stats: [
        [
          1,
          "Time on Defense Guarding PG_pct",
          currentPlayer["Time on Defense Guarding PG_pct"],
          percentileScores["Time on Defense Guarding PG_pct"],
          playerGrades["Time on Defense Guarding PG_pct"],
        ],
        [
          1,
          "Time on Defense Guarding SG_pct",
          currentPlayer["Time on Defense Guarding SG_pct"],
          percentileScores["Time on Defense Guarding SG_pct"],
          playerGrades["Time on Defense Guarding SG_pct"],
        ],
        [
          1,
          "Time on Defense Guarding SF_pct",
          currentPlayer["Time on Defense Guarding SF_pct"],
          percentileScores["Time on Defense Guarding SF_pct"],
          playerGrades["Time on Defense Guarding SF_pct"],
        ],
        [
          1,
          "Time on Defense Guarding PF_pct",
          currentPlayer["Time on Defense Guarding PF_pct"],
          percentileScores["Time on Defense Guarding PF_pct"],
          playerGrades["Time on Defense Guarding PF_pct"],
        ],
        [
          1,
          "Time on Defense Guarding C_pct",
          currentPlayer["Time on Defense Guarding C_pct"],
          percentileScores["Time on Defense Guarding C_pct"],
          playerGrades["Time on Defense Guarding C_pct"],
        ],
      ],
    },
    {
      title: "Usage by Tier",
      vsaverage: false,
      stats: [
        [
          1,
          "Usage Tier 1_pct",
          currentPlayer["Usage Tier 1_pct"],
          percentileScores["Usage Tier 1_pct"],
          playerGrades["Usage Tier 1_pct"],
        ],
        [
          2,
          "Usage Tier 2_pct",
          currentPlayer["Usage Tier 2_pct"],
          percentileScores["Usage Tier 2_pct"],
          playerGrades["Usage Tier 2_pct"],
        ],
        [
          2,
          "Usage Tier 3_pct",
          currentPlayer["Usage Tier 3_pct"],
          percentileScores["Usage Tier 3_pct"],
          playerGrades["Usage Tier 3_pct"],
        ],
        [
          3,
          "Usage Tier 4_pct",
          currentPlayer["Usage Tier 4_pct"],
          percentileScores["Usage Tier 4_pct"],
          playerGrades["Usage Tier 4_pct"],
        ],
        [
          3,
          "Usage Tier 5_pct",
          currentPlayer["Usage Tier 5_pct"],
          percentileScores["Usage Tier 5_pct"],
          playerGrades["Usage Tier 5_pct"],
        ],
        [
          3,
          "Usage Tier 6_pct",
          currentPlayer["Usage Tier 6_pct"],
          percentileScores["Usage Tier 6_pct"],
          playerGrades["Usage Tier 6_pct"],
        ],
      ],
    },
    {
      title: "Player Role",
      vsaverage: false,
      stats: [
        [
          1,
          "Core Player_pct",
          currentPlayer["Core Player_pct"],
          percentileScores["Core Player_pct"],
          playerGrades["Core Player_pct"],
        ],
        [
          2,
          "Starter_pct",
          currentPlayer["Starter_pct"],
          percentileScores["Starter_pct"],
          playerGrades["Starter_pct"],
        ],
        [
          3,
          "All Star Player_pct",
          currentPlayer["All Star Player_pct"],
          percentileScores["All Star Player_pct"],
          playerGrades["All Star Player_pct"],
        ],
        [
          3,
          "All NBA Player_pct",
          currentPlayer["All NBA Player_pct"],
          percentileScores["All NBA Player_pct"],
          playerGrades["All NBA Player_pct"],
        ],
      ],
    },
    {
      title: "Advanced Metrics",
      vsaverage: false,
      stats: [
        [
          1,
          "LEBRON",
          currentPlayer["LEBRON"],
          percentileScores["LEBRON"],
          playerGrades["LEBRON"],
        ],
        [
          1,
          "O-LEBRON",
          currentPlayer["O-LEBRON"],
          percentileScores["O-LEBRON"],
          playerGrades["O-LEBRON"],
        ],
        [
          1,
          "D-LEBRON",
          currentPlayer["D-LEBRON"],
          percentileScores["D-LEBRON"],
          playerGrades["D-LEBRON"],
        ],
        [
          1,
          "LEBRON WAR",
          currentPlayer["LEBRON WAR"],
          percentileScores["LEBRON WAR"],
          playerGrades["LEBRON WAR"],
        ],
        [
          2,
          "Real Plus Minus (RPM)",
          currentPlayer["Real Plus Minus (RPM)"],
          percentileScores["Real Plus Minus (RPM)"],
          playerGrades["Real Plus Minus (RPM)"],
        ],
        [
          2,
          "Offensive RPM",
          currentPlayer["Offensive RPM"],
          percentileScores["Offensive RPM"],
          playerGrades["Offensive RPM"],
        ],
        [
          2,
          "Defensive RPM",
          currentPlayer["Defensive RPM"],
          percentileScores["Defensive RPM"],
          playerGrades["Defensive RPM"],
        ],
        [
          3,
          "RPM WAR",
          currentPlayer["RPM WAR"],
          percentileScores["RPM WAR"],
          playerGrades["RPM WAR"],
        ],
        [
          3,
          "RAPTOR",
          currentPlayer["RAPTOR"],
          percentileScores["RAPTOR"],
          playerGrades["RAPTOR"],
        ],
        [
          3,
          "Offensive RAPTOR",
          currentPlayer["Offensive RAPTOR"],
          percentileScores["Offensive RAPTOR"],
          playerGrades["Offensive RAPTOR"],
        ],
        [
          3,
          "Defensive RAPTOR",
          currentPlayer["Defensive RAPTOR"],
          percentileScores["Defensive RAPTOR"],
          playerGrades["Defensive RAPTOR"],
        ],
        [
          3,
          "RAPTOR WAR",
          currentPlayer["RAPTOR WAR"],
          percentileScores["RAPTOR WAR"],
          playerGrades["RAPTOR WAR"],
        ],
        [
          3,
          "LA RAPM",
          currentPlayer["LA RAPM"],
          percentileScores["LA RAPM"],
          playerGrades["LA RAPM"],
        ],
        [
          3,
          "LA-ORAPM",
          currentPlayer["LA-ORAPM"],
          percentileScores["LA-ORAPM"],
          playerGrades["LA-ORAPM"],
        ],
        [
          3,
          "LA-DRAPM",
          currentPlayer["LA-DRAPM"],
          percentileScores["LA-DRAPM"],
          playerGrades["LA-DRAPM"],
        ],
        [
          3,
          "LEBRON Box",
          currentPlayer["LEBRON Box"],
          percentileScores["LEBRON Box"],
          playerGrades["LEBRON Box"],
        ],
        [
          3,
          "O-LEBRON Box",
          currentPlayer["O-LEBRON Box"],
          percentileScores["O-LEBRON Box"],
          playerGrades["O-LEBRON Box"],
        ],
        [
          3,
          "D-LEBRON Box",
          currentPlayer["D-LEBRON Box"],
          percentileScores["D-LEBRON Box"],
          playerGrades["D-LEBRON Box"],
        ],
        [
          3,
          "Box Plus Minus 2.0 (BPM)",
          currentPlayer["Box Plus Minus 2.0 (BPM)"],
          percentileScores["Box Plus Minus 2.0 (BPM)"],
          playerGrades["Box Plus Minus 2.0 (BPM)"],
        ],
      ],
    },
    {
      title: "DK Fantasy Stats",
      vsaverage: false,
      stats: [
        [
          1,
          "DK Fantasy Points/75",
          currentPlayer["DK Fantasy Points/75"],
          percentileScores["DK Fantasy Points/75"],
          playerGrades["DK Fantasy Points/75"],
        ],
        [
          2,
          "Points/75",
          currentPlayer["Points/75"],
          percentileScores["Points/75"],
          playerGrades["Points/75"],
        ],
        [
          2,
          "3PM/75",
          currentPlayer["3PM/75"],
          percentileScores["3PM/75"],
          playerGrades["3PM/75"],
        ],
        [
          2,
          "Reb/75",
          currentPlayer["Reb/75"],
          percentileScores["Reb/75"],
          playerGrades["Reb/75"],
        ],
        [
          2,
          "Ast/75",
          currentPlayer["Ast/75"],
          percentileScores["Ast/75"],
          playerGrades["Ast/75"],
        ],
        [
          2,
          "Stl/75",
          currentPlayer["Stl/75"],
          percentileScores["Stl/75"],
          playerGrades["Stl/75"],
        ],
        [
          2,
          "Blk/75",
          currentPlayer["Blk/75"],
          percentileScores["Blk/75"],
          playerGrades["Blk/75"],
        ],
        [
          2,
          "TOV/75",
          currentPlayer["TOV/75"],
          percentileScores["TOV/75"],
          playerGrades["TOV/75"],
        ],
        [
          2,
          "PF/75",
          currentPlayer["PF/75"],
          percentileScores["PF/75"],
          playerGrades["PF/75"],
        ],
      ],
    },
    {
      title: "DK Fantasy",
      vsaverage: false,
      stats: [
        [
          1,
          "Effective FG_pct",
          currentPlayer["Effective FG_pct"],
          percentileScores["Effective FG_pct"],
          playerGrades["Effective FG_pct"],
        ],
        [
          2,
          "True Shooting_pct",
          currentPlayer["True Shooting_pct"],
          percentileScores["True Shooting_pct"],
          playerGrades["True Shooting_pct"],
        ],
        [
          2,
          "Points Per Shot",
          currentPlayer["Points Per Shot"],
          percentileScores["Points Per Shot"],
          playerGrades["Points Per Shot"],
        ],
        [
          3,
          "Points/Possession (PPP)",
          currentPlayer["Points/Possession (PPP)"],
          percentileScores["Points/Possession (PPP)"],
          playerGrades["Points/Possession (PPP)"],
        ],
        [
          3,
          "Points Over Expectation",
          currentPlayer["Points Over Expectation"],
          percentileScores["Points Over Expectation"],
          playerGrades["Points Over Expectation"],
        ],
        [
          3,
          "Stable Transition PPP",
          currentPlayer["Stable Transition PPP"],
          percentileScores["Stable Transition PPP"],
          playerGrades["Stable Transition PPP"],
        ],
        [
          3,
          "Stable P&R Ball Handler PPP",
          currentPlayer["Stable P&R Ball Handler PPP"],
          percentileScores["Stable P&R Ball Handler PPP"],
          playerGrades["Stable P&R Ball Handler PPP"],
        ],
        [
          3,
          "Stable Spot Up PPP",
          currentPlayer["Stable Spot Up PPP"],
          percentileScores["Stable Spot Up PPP"],
          playerGrades["Stable Spot Up PPP"],
        ],
        [
          3,
          "Stable P&R Roll Man PPP",
          currentPlayer["Stable P&R Roll Man PPP"],
          percentileScores["Stable P&R Roll Man PPP"],
          playerGrades["Stable P&R Roll Man PPP"],
        ],
        [
          3,
          "Stable Post Up PPP",
          currentPlayer["Stable Post Up PPP"],
          percentileScores["Stable Post Up PPP"],
          playerGrades["Stable Post Up PPP"],
        ],
        [
          3,
          "Stable Isolation PPP",
          currentPlayer["Stable Isolation PPP"],
          percentileScores["Stable Isolation PPP"],
          playerGrades["Stable Isolation PPP"],
        ],
        [
          3,
          "Stable Cut PPP",
          currentPlayer["Stable Cut PPP"],
          percentileScores["Stable Cut PPP"],
          playerGrades["Stable Cut PPP"],
        ],
        [
          3,
          "Stable Dump Offs PPP",
          currentPlayer["Stable Dump Offs PPP"],
          percentileScores["Stable Dump Offs PPP"],
          playerGrades["Stable Dump Offs PPP"],
        ],
        [
          3,
          "Stable Putbacks PPP",
          currentPlayer["Stable Putbacks PPP"],
          percentileScores["Stable Putbacks PPP"],
          playerGrades["Stable Putbacks PPP"],
        ],
        [
          3,
          "Handoff PPP",
          currentPlayer["Handoff PPP"],
          percentileScores["Handoff PPP"],
          playerGrades["Handoff PPP"],
        ],
        [
          3,
          "Stable Off Screen PPP",
          currentPlayer["Stable Off Screen PPP"],
          percentileScores["Stable Off Screen PPP"],
          playerGrades["Stable Off Screen PPP"],
        ],
      ],
    },
  ];
};

export default FullDataTable;
